[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.22", default-features = false, features = ["toml"] }
vec3 = { path = "crates/vec3" }
orientation = { path = "crates/orientation" }
ray = { path = "crates/ray" }
color = { path = "crates/color" }
camera = { path = "crates/camera" }
object_interface = { path = "crates/objects/object_interface" }
light_interface = { path = "crates/lights/light_interface" }
omni_light = { path = "crates/lights/omni_light" }
ambiant = { path = "crates/lights/ambiant" }
directional_light = { path = "crates/lights/directional_light" }
plane = { path = "crates/objects/plane" }
sphere = { path = "crates/objects/sphere" }
cylinder = { path = "crates/objects/cylinder" }
cone = { path = "crates/objects/cone" }
triangle = { path = "crates/objects/triangle" }
obj_file = { path = "crates/objects/obj_file" }
