[render]
width = 1000
height = 1000

[camera]
fov = 120.0
position = { depth = -8.0, right = 0.0, up = 0.0 }
direction = { depth = 1.0, right = 0.0, up = 0.0 }

[[lights.omni]]
position = { depth = -2.0, right = 0.0, up = 0.0 }
color = { r = 255, g = 255, b = 255 }
intensity = 10.0


[[lights.ambiant]]
color = { r = 255, g = 255, b = 255 }
intensity = 0.2

[[objects.obj_file]]
path = "configs/assets/object.obj"
position = { depth = 0.0, right = 0.0, up = 0.0 }
orientation = { p = 0.0, y = 270.0, r = 0.0 }
reflectivity = 25