[render]
width = 500
height = 500

[camera]
fov = 40.0
position = { depth = -10.0, right = 5.0, up = 10.0 }
direction = { depth = 1.0, right = -0.5, up = -1 }

[[lights.directional]]
direction = { depth = 0.05, right = 0.05, up = -1.0 }
color = { r = 255, g = 255, b = 255 }
intensity = 1.5

[[lights.ambiant]]
color = { r = 255, g = 255, b = 255 }
intensity = 0.1

[[objects.plane]]
position = { depth = 0.0, right = 0.0, up = -1.0 }
orientation = { depth = 0.0, right = 0.0, up = 1.0 }
color = { r = 10, g = 10, b = 10 }
reflectivity = 10

[[objects.obj_file]]
path = "configs/assets/raytracer_text.obj"
position = { depth = 0.0, right = 0.0, up = 0.0 }
orientation = { p = 0.0, y = 0.0, r = 0.0 }
color = { r = 255, g = 255, b = 255 }

#[scenes]
#list = ["showcase_pedestrals.toml"]
#list = ["showcase_objects.toml"]
list = ["showcase_pedestrals.toml", "showcase_objects.toml"]
